### ISSUE TITLE
Several errors in the logs and missing avatars, logo and images

### ISSUE THREAD

**Issue by kboykov** [espocrm/espocrm#2097]
Hello,

We are having several issues after upgrading to 7.0 and 7.0.1... The main problem is that our avatars and main logo for the CRM are not being loaded. (getting error 500 from the EntryPoint request). There does not seem to be errors in the logs regarding this problem.

Environment:
PHP 7.4, Litespeed, Ubuntu 20.04

Some of the errors which can be found after upgrading:
`[2021-10-05 08:49:26] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []
[2021-10-05 08:49:29] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []
[2021-10-05 08:50:14] ERROR: Slim Application Error Type: TypeError Code: 0 Message: Return value of Espo\Services\User::getEntity() must implement interface Espo\ORM\Entity, null returned File: /home/demo.obfuscated.com/public_html/application/Espo/Services/User.php Line: 91 Trace: #0 /home/demo.obfuscated.com/public_html/application/Espo/Core/Record/Service.php(272): Espo\Services\User->getEntity() #1 /home/demo.obfuscated.com/public_html/application/Espo/Core/Controllers/RecordBase.php(168): Espo\Core\Record\Service->read() #2 /home/demo.obfuscated.com/public_html/application/Espo/Core/Api/ActionProcessor.php(95): Espo\Core\Controllers\RecordBase->getActionRead() #3 /home/demo.obfuscated.com/public_html/application/Espo/Core/Api/RequestProcessor.php(136): Espo\Core\Api\ActionProcessor->process() #4 /home/demo.obfuscated.com/public_html/application/Espo/Core/Api/RequestProcessor.php(111): Espo\Core\Api\RequestProcessor->proceed() #5 /home/demo.obfuscated.com/public_html/application/Espo/Core/Api/RequestProcessor.php(82): Espo\Core\Api\RequestProcessor->processInternal() #6 /home/demo.obfuscated.com/public_html/application/Espo/Core/Api/Starter.php(103): Espo\Core\Api\RequestProcessor->process() #7 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Espo\Core\Api\Starter->Espo\Core\Api\{closure}() #8 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke() #9 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle() #10 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle() #11 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle() #12 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run() #13 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle() #14 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process() #15 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle() #16 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process() #17 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle() #18 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle() #19 /home/demo.obfuscated.com/public_html/vendor/slim/slim/Slim/App.php(199): Slim\App->handle() #20 /home/demo.obfuscated.com/public_html/application/Espo/Core/Api/Starter.php(79): Slim\App->run() #21 /home/demo.obfuscated.com/public_html/application/Espo/Core/ApplicationRunners/Api.php(49): Espo\Core\Api\Starter->start() #22 /home/demo.obfuscated.com/public_html/application/Espo/Core/Application/RunnerRunner.php(85): Espo\Core\ApplicationRunners\Api->run() #23 /home/demo.obfuscated.com/public_html/application/Espo/Core/Application.php(78): Espo\Core\Application\RunnerRunner->run() #24 /home/demo.obfuscated.com/public_html/public/api/v1/index.php(37): Espo\Core\Application->run() #25 {main} Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
[2021-10-05 08:58:47] ERROR: (0) Access checker is not implemented for 'Settings'.; POST /Attachment; line: 88, file: /home/demo.obfuscated.com/public_html/application/Espo/Core/Acl/AccessChecker/AccessCheckerFactory.php [] []
[2021-10-05 08:58:59] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []
[2021-10-05 08:58:59] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []
[2021-10-05 08:58:59] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []
`

I have created the necessary webserver configurations as stated in the Wiki. (public and client folder) but still every EntryPoint request gives me error 500 trying to load image, logo, file, avatar.

**Comment by yurikuzn** [comment]
Error fix: https://github.com/espocrm/espocrm/commit/7cd332228a84cf9f2fb20d10344f7611c7984604

**Comment by kboykov** [comment]
[2021-10-05 08:58:47] ERROR: (0) Access checker is not implemented for 'Settings'.; POST /Attachment; line: 88, file: /home/demo.obfuscated.com/public_html/application/Espo/Core/Acl/AccessChecker/AccessCheckerFactory.php [] []

[2021-10-05 08:58:59] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []

[2021-10-05 08:58:59] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []

[2021-10-05 08:58:59] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []

[2021-10-05 13:06:17] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []

[2021-10-05 13:06:17] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []

[2021-10-05 13:06:17] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []

[2021-10-05 13:06:18] WARNING: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/home/demo.obfuscated.com/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":379} []

**Comment by yurikuzn** [comment]
Could you help with debugging?

**Comment by kboykov** [comment]
Sure... Just tell me what do I need to do. 
After trying everything possible, my staging instance is still half broken, no avatars, no images, no attachments. It's like every EntryPoint is not working properly for some reason.

**Comment by yurikuzn** [comment]
I'm very overwhelmed with upgrade help request. Sorry.

**Comment by yurikuzn** [comment]
I could produce the error that logo can't be uploaded. Here's the fix: https://github.com/espocrm/espocrm/commit/83ac300aa37dc88bfef24960b18ca90e67f75755

Do you you have issue with uploading or displaying?

I could not reproduce the issue with avatars.

**Comment by kboykov** [comment]
I can confirm that I can successfully upload the files, but they cannot display on the front-end. (Even after both fixes being applied manually)
I will try to reproduce the problems by freshly installing 7.0.1 in the same environment.
Thank you for your hard work, Yuri.

**Comment by llsatellite** [comment]
Im having the same problem but those links are not working anymore ca someone point me in the right direction on how to get it fix
