### ISSUE TITLE
Extension upgrade error 

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2237]
**Describe the bug**
When an Extension has custom saver or hook for example, extension first upload will fail first time and we have to fire upload buttom once more again to let it work.

**To Reproduce**
1. define a csutom saver on an extension
2. upload the extension twice.

**Expected behavior**
I expect espo to disable cache before uninstalling the old copy of extension and restore the cache value after it uninstalled 

**EspoCRM version**
Latest version

**Additional context**
I suggest to disable the cache just like the crm upgrade does, maybe temporarily stopping the cronjob makes sense as well (not sure about this).

**Comment by eymen-elkum** [comment]
[2022-02-22 05:26:22] ERROR: Error saving Extension entity. The error occurred by existing Hook, more details: InjectableFactory: Class 'Espo\Modules\XXXXX\Core\FieldProcessing\LinkMultiple\Saver' does not exist. at /home/eymendev/public_html/application/Espo/Core/InjectableFactory.php:68 [] []
[2022-02-22 05:26:23] ERROR: (500) Error saving Extension entity. Check logs for details.; POST /Extension/action/install; line: 166, file: /home/eymendev/public_html/application/Espo/Core/Upgrades/Actions/Base.php [] []

**Comment by yurikuzn** [comment]
Could you provide a trace please? "ptintTrace": true https://docs.espocrm.com/administration/log/#parameters

**Comment by eymen-elkum** [comment]
[2022-02-22 11:39:06] ERROR: Error saving Extension entity. The error occurred by existing Hook, more details: InjectableFactory: Class 'Espo\Modules\ModuleName\Tools\Stream\HookProcessor' does not exist. at /app/code/7.0.9/application/Espo/Core/InjectableFactory.php:112 [] []
[2022-02-22 11:39:11] ERROR: (500) Error saving Extension entity. Check logs for details.; POST /Extension/action/install; line: 197, file: /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Base.php :: #0 /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Base/Uninstall.php(176): Espo\Core\Upgrades\Actions\Base->
throwErrorAndRemovePackage() #1 /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Extension/Uninstall.php(74): Espo\Core\Upgrades\Actions\Base\Uninstall->throwErrorAndRemovePackage() #2 /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Base/Uninstall.php(95): Espo\Core\Upgrades\Actions\Extension\Uninstall->
afterRunAction() #3 /app/code/7.0.9/application/Espo/Core/Upgrades/ActionManager.php(84): Espo\Core\Upgrades\Actions\Base\Uninstall->run() #4 /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Base.php(836): Espo\Core\Upgrades\ActionManager->run() #5 /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Extension/Install.php(
215): Espo\Core\Upgrades\Actions\Base->executeAction() #6 /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Extension/Install.php(50): Espo\Core\Upgrades\Actions\Extension\Install->uninstallExtension() #7 /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Base/Install.php(115):
Espo\Core\Upgrades\Actions\Extension\Install->beforeRunAction() #8 /app/code/7.0.9/application/Espo/Core/Upgrades/Actions/Base/Install.php(47): Espo\Core\Upgrades\Actions\Base\Install->stepInit() #9 /app/code/7.0.9/application/Espo/Core/Upgrades/ActionManager.php(84): Espo\Core\Upgrades\Actions\Base\Install->run() #10
/app/code/7.0.9/application/Espo/Core/Upgrades/Base.php(93): Espo\Core\Upgrades\ActionManager->run() #11 /app/code/7.0.9/application/Espo/Controllers/Extension.php(80): Espo\Core\Upgrades\Base->install() #12 /app/code/7.0.9/application/Espo/Core/Api/ActionProcessor.php(97): Espo\Controllers\Extension->postActionInstall() #13
/app/code/7.0.9/application/Espo/Core/Api/RequestProcessor.php(136): Espo\Core\Api\ActionProcessor->process() #14 /app/code/7.0.9/application/Espo/Core/Api/RequestProcessor.php(111): Espo\Core\Api\RequestProcessor->proceed() #15 /app/code/7.0.9/application/Espo/Core/Api/RequestProcessor.php(82): Espo\Core\Api\RequestProcessor->
processInternal() #16 /app/code/7.0.9/application/Espo/Core/Api/Starter.php(103): Espo\Core\Api\RequestProcessor->process() #17 /app/code/7.0.9/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Espo\Core\Api\Starter->Espo\Core\Api\{closure}() #18 /app/code/7.0.9/vendor/slim/slim/Slim/Routing/Route.php(384):
Slim\Handlers\Strategies\RequestResponse->__invoke() #19 /app/code/7.0.9/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle() #20 /app/code/7.0.9/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle() #21 /app/code/7.0.9/vendor/slim/slim/Slim/Routing/Route.php(341):
Slim\MiddlewareDispatcher->handle() #22 /app/code/7.0.9/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run() #23 /app/code/7.0.9/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle() #24 /app/code/7.0.9/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147):
Slim\Middleware\RoutingMiddleware->process() #25 /app/code/7.0.9/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle() #26 /app/code/7.0.9/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process() #27 /app/code/7.0.9/vendor/slim/slim/Slim/MiddlewareDispatcher.php(
81): class@anonymous->handle() #28 /app/code/7.0.9/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle() #29 /app/code/7.0.9/vendor/slim/slim/Slim/App.php(199): Slim\App->handle() #30 /app/code/7.0.9/application/Espo/Core/Api/Starter.php(79): Slim\App->run() #31
/app/code/7.0.9/application/Espo/Core/ApplicationRunners/Api.php(49): Espo\Core\Api\Starter->start() #32 /app/code/7.0.9/application/Espo/Core/Application/RunnerRunner.php(85): Espo\Core\ApplicationRunners\Api->run() #33 /app/code/7.0.9/application/Espo/Core/Application.php(78): Espo\Core\Application\RunnerRunner->run() #34
/app/code/7.0.9/public/api/v1/index.php(37): Espo\Core\Application->run() #35 {main} [] []

**Comment by yurikuzn** [comment]
Thanks. This should fix the problem I hope: https://github.com/espocrm/espocrm/commit/930f45b93aee8648b5541001c0bf0dfeed6b1d6f

**Comment by eymen-elkum** [comment]
Yes fixed, thanks!
