### ISSUE TITLE
Error run npm ci

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2354]
**Describe the bug**
Error run npm ci

**EspoCRM version**
Git master

**Additional context**
npm WARN skipping integrity check for git dependency ssh://git@github.com/yurikuzn/moment-timezone-data-build.git 
npm WARN skipping integrity check for git dependency ssh://git@github.com/yurikuzn/espo-funnel-chart.git 
npm WARN deprecated vis@4.19.1: Please consider using https://github.com/visjs

> espocrm@7.1.7 postinstall
> node js/scripts/postinstall-cleanup && node js/scripts/prepare-lib-original.js

C:\Application\espocrm\js\scripts\prepare-lib-original.js:54
    let re = /\/\/\# sourceMappingURL.*/dg;
             ^

SyntaxError: Invalid regular expression flags
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path C:\Application\espocrm
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\xxx\AppData\Local\Temp\postinstall-1656394977722.cmd

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2022-06-28T05_41_17_249Z-debug-0.log

File log
[2022-06-28T05_41_17_249Z-debug-0.log](https://github.com/espocrm/espocrm/files/8998050/2022-06-28T05_41_17_249Z-debug-0.log)

**Comment by yurikuzn** [comment]
Should work now.
