### ISSUE TITLE
User::checkBelongsToAnyOfTeams(): Argument #2 ($teamIds) must be of type array, null given

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#2909]
**Describe the bug**
I am trying to create a role:
A Role - a role for salesman that should have access to "own" accounts with "team" assignment permissions.
A Role Leader - a team leader role that is able to see all accounts from A Role users
Espo however throws error 500 after user with "A Role" tries to create account.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. ![image](https://github.com/espocrm/espocrm/assets/15276167/b33e3b6b-ddee-4455-87bc-445f004c6b09)
2. ![image](https://github.com/espocrm/espocrm/assets/15276167/14f817a3-8fd0-4546-b1f1-5759b94009a4)
3. ![image](https://github.com/espocrm/espocrm/assets/15276167/4b30f830-1cd1-4462-8454-d996b54b23b9)
4. ![image](https://github.com/espocrm/espocrm/assets/15276167/6b110026-e1d6-494b-8b42-6642bd47ab44)
5. ![image](https://github.com/espocrm/espocrm/assets/15276167/e7ce8d33-20a9-46aa-919b-08fe9a7bdf2b)

**Expected behavior**
User should be able to create records, because
a) he can create records that are assigned to him
b) he is assigning the record to a correct team that he is part of

**Screenshots**
Above

**EspoCRM version**
Happens both on 7.5 and 8.0.5, even tried on brand new install with no custom modifications

**Additional context**
While writing this issue, it occured to me that the user might not have permissions to view team members because role does not allow it. But even after allowing to read "all" teams the issue still persists.

**Comment by radek3911** [comment]
```log
[2023-11-23 21:06:44] ERROR: Slim Application Error Type: TypeError Code: 0 Message: Espo\Repositories\User::checkBelongsToAnyOfTeams(): Argument #2 ($teamIds) must be of type array, null given, called in /home/radek.devcrm.cz/public_html/application/Espo/Core/Acl/DefaultAssignmentChecker.php on line 147 File: /home/radek.devcrm.cz/public_html/application/Espo/Repositories/User.php Line: 120 Trace: #0 /home/radek.devcrm.cz/public_html/application/Espo/Core/Acl/DefaultAssignmentChecker.php(147): Espo\Repositories\User->checkBelongsToAnyOfTeams() #1 /home/radek.devcrm.cz/public_html/application/Espo/Core/Acl/DefaultAssignmentChecker.php(62): Espo\Core\Acl\DefaultAssignmentChecker->isPermittedAssignedUser() #2 /home/radek.devcrm.cz/public_html/application/Espo/Core/Acl/AssignmentChecker/AssignmentCheckerManager.php(50): Espo\Core\Acl\DefaultAssignmentChecker->check() #3 /home/radek.devcrm.cz/public_html/application/Espo/Core/Record/Service.php(409): Espo\Core\Acl\AssignmentChecker\AssignmentCheckerManager->check() #4 /home/radek.devcrm.cz/public_html/application/Espo/Core/Record/Service.php(397): Espo\Core\Record\Service->checkAssignment() #5 /home/radek.devcrm.cz/public_html/application/Espo/Core/Record/Service.php(697): Espo\Core\Record\Service->processAssignmentCheck() #6 /home/radek.devcrm.cz/public_html/application/Espo/Core/Controllers/RecordBase.php(181): Espo\Core\Record\Service->create() #7 /home/radek.devcrm.cz/public_html/application/Espo/Core/Api/ControllerActionProcessor.php(87): Espo\Core\Controllers\RecordBase->postActionCreate() #8 /home/radek.devcrm.cz/public_html/application/Espo/Core/Api/ControllerActionHandler.php(65): Espo\Core\Api\ControllerActionProcessor->process() #9 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Espo\Core\Api\ControllerActionHandler->handle() #10 /home/radek.devcrm.cz/public_html/application/Espo/Core/Api/RouteProcessor.php(222): Slim\MiddlewareDispatcher->handle() #11 /home/radek.devcrm.cz/public_html/application/Espo/Core/Api/RouteProcessor.php(149): Espo\Core\Api\RouteProcessor->processControllerAction() #12 /home/radek.devcrm.cz/public_html/application/Espo/Core/Api/RouteProcessor.php(127): Espo\Core\Api\RouteProcessor->processAfterAuth() #13 /home/radek.devcrm.cz/public_html/application/Espo/Core/Api/RouteProcessor.php(78): Espo\Core\Api\RouteProcessor->processInternal() #14 /home/radek.devcrm.cz/public_html/application/Espo/Core/Api/Starter.php(109): Espo\Core\Api\RouteProcessor->process() #15 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Espo\Core\Api\Starter->Espo\Core\Api\{closure}() #16 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke() #17 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle() #18 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle() #19 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle() #20 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run() #21 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Slim\Routing\RouteRunner->handle() #22 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process() #23 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #24 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process() #25 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #26 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle() #27 /home/radek.devcrm.cz/public_html/vendor/slim/slim/Slim/App.php(183): Slim\App->handle() #28 /home/radek.devcrm.cz/public_html/application/Espo/Core/Api/Starter.php(76): Slim\App->run() #29 /home/radek.devcrm.cz/public_html/application/Espo/Core/ApplicationRunners/Api.php(45): Espo\Core\Api\Starter->start() #30 /home/radek.devcrm.cz/public_html/application/Espo/Core/Application/RunnerRunner.php(84): Espo\Core\ApplicationRunners\Api->run() #31 /home/radek.devcrm.cz/public_html/application/Espo/Core/Application.php(78): Espo\Core\Application\RunnerRunner->run() #32 /home/radek.devcrm.cz/public_html/public/api/v1/index.php(35): Espo\Core\Application->run() #33 {main} Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
```

**Comment by radek3911** [comment]
Closing - I just realized that it's now fixed in master branch
https://github.com/espocrm/espocrm/commit/312be1dfc1cd65660ec11a3ac38984772eb285b0

**Comment by yurikuzn** [comment]
Does it happen only when an admin logs as another user?

**Comment by radek3911** [comment]
Strangely enough it does not seems to.

Initially I did not even use the login option as we have our own "impersonation" feature. I tried with both "our impersonation" and "login as user" from espo.

But when I logged in as the user it did not seem to occur.

**Comment by yurikuzn** [comment]
It occurred only when 'login as user' used. We already fixed.
