### ISSUE TITLE
Depracated preferences relation?

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#2989]
**Describe the bug**
I am trying to use preferences relation in formula script (context entity is User)

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Go to formula sandbox
2. Target entity: User, select random user
3. Try command output\printLine(preferences.signature);

After running error 500 is returned

**Expected behavior**
Formula sandbox returns field value.

**Screenshots**
N/A

**EspoCRM version**
8.1.0

**Additional context**
Espo log:
```
DEBUG: API (42S22) SQLSTATE[42S22]: Column not found: 1054 Unknown column 'preferences.time_zone' in 'field list'; POST /Formula/action/run; Input data: {"expression":"output\\printLine(preferences.dashboardLayout)","targetId":"6470eecb0bfcde51a","targetType":"User"}; Route pattern: /{controller}/action/{action}; Route params: Array (     [controller] => Formula     [action] => run )   
[2024-02-15 23:50:19] ERROR: (42S22) SQLSTATE[42S22]: Column not found: 1054 Unknown column 'preferences.time_zone' in 'field list'; POST /Formula/action/run; line: 76, file: /home/xxxxxxxxxxx/public_html/application/Espo/ORM/Executor/DefaultSqlExecutor.php :: #0 /home/xxxxxxxxxxx/public_html/application/Espo/ORM/Executor/DefaultSqlExecutor.php(76): PDO->query() #1 /home/xxxxxxxxxxx/public_html/application/Espo/ORM/Executor/DefaultSqlExecutor.php(68): Espo\ORM\Executor\DefaultSqlExecutor->executeSqlWithDeadlockHandling() #2 /home/xxxxxxxxxxx/public_html/application/Espo/ORM/Executor/DefaultQueryExecutor.php(48): Espo\ORM\Executor\DefaultSqlExecutor->execute() #3 /home/xxxxxxxxxxx/public_html/application/Espo/ORM/Mapper/BaseMapper.php(400): Espo\ORM\Executor\DefaultQueryExecutor->execute() #4 /home/xxxxxxxxxxx/public_html/application/Espo/ORM/Mapper/BaseMapper.php(264): Espo\ORM\Mapper\BaseMapper->selectRelatedInternal() #5 /home/xxxxxxxxxxx/public_html/application/Espo/ORM/Repository/RDBRelationSelectBuilder.php(197): Espo\ORM\Mapper\BaseMapper->selectRelated() #6 /home/xxxxxxxxxxx/public_html/application/Espo/ORM/Repository/RDBRelation.php(187): Espo\ORM\Repository\RDBRelationSelectBuilder->find() #7 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/AttributeFetcher.php(70): Espo\ORM\Repository\RDBRelation->findOne() #8 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/Functions/AttributeType.php(70): Espo\Core\Formula\AttributeFetcher->fetch() #9 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/Functions/AttributeType.php(60): Espo\Core\Formula\Functions\AttributeType->getAttributeValue() #10 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/Processor.php(114): Espo\Core\Formula\Functions\AttributeType->process() #11 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/Functions/BaseFunction.php(97): Espo\Core\Formula\Processor->process() #12 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/Functions/OutputGroup/PrintLineType.php(45): Espo\Core\Formula\Functions\BaseFunction->evaluate() #13 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/Processor.php(117): Espo\Core\Formula\Functions\OutputGroup\PrintLineType->process() #14 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/Evaluator.php(88): Espo\Core\Formula\Processor->process() #15 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Formula/Manager.php(60): Espo\Core\Formula\Evaluator->process() #16 /home/xxxxxxxxxxx/public_html/application/Espo/Tools/Formula/Service.php(96): Espo\Core\Formula\Manager->run() #17 /home/xxxxxxxxxxx/public_html/application/Espo/Controllers/Formula.php(85): Espo\Tools\Formula\Service->run() #18 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Api/ControllerActionProcessor.php(87): Espo\Controllers\Formula->postActionRun() #19 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Api/ControllerActionHandler.php(65): Espo\Core\Api\ControllerActionProcessor->process() #20 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Espo\Core\Api\ControllerActionHandler->handle() #21 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Api/RouteProcessor.php(222): Slim\MiddlewareDispatcher->handle() #22 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Api/RouteProcessor.php(149): Espo\Core\Api\RouteProcessor->processControllerAction() #23 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Api/RouteProcessor.php(127): Espo\Core\Api\RouteProcessor->processAfterAuth() #24 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Api/RouteProcessor.php(78): Espo\Core\Api\RouteProcessor->processInternal() #25 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Api/Starter.php(109): Espo\Core\Api\RouteProcessor->process() #26 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Espo\Core\Api\Starter->Espo\Core\Api\{closure}() #27 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke() #28 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle() #29 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle() #30 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle() #31 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run() #32 /home/xxxxxxxxxxx/public_html/application/Espo/Modules/Sentry/Classes/Middlewares/SentryTransaction.php(17): Slim\Routing\RouteRunner->handle() #33 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Espo\Modules\Sentry\Classes\Middlewares\SentryTransaction->process() #34 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #35 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process() #36 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #37 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process() #38 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #39 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle() #40 /home/xxxxxxxxxxx/public_html/vendor/slim/slim/Slim/App.php(183): Slim\App->handle() #41 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Api/Starter.php(76): Slim\App->run() #42 /home/xxxxxxxxxxx/public_html/application/Espo/Core/ApplicationRunners/Api.php(45): Espo\Core\Api\Starter->start() #43 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Application/RunnerRunner.php(84): Espo\Core\ApplicationRunners\Api->run() #44 /home/xxxxxxxxxxx/public_html/application/Espo/Core/Application.php(78): Espo\Core\Application\RunnerRunner->run() #45 /home/xxxxxxxxxxx/public_html/public/api/v1/index.php(35): Espo\Core\Application->run() #46 {main}
```

I am not sure whether this is supported anymore, but the relation is being code suggested in the formula sandbox
![image](https://github.com/espocrm/espocrm/assets/15276167/2240e368-390b-4366-ba05-28f84f776cb6)

This however works:
output\printLine(record\attribute('Preferences', id, 'signature'));

so this is probably some deprecated leftover in espo

**Comment by yurikuzn** [comment]
Removed it: https://github.com/espocrm/espocrm/commit/a9dc3a62fba704578284e36fe7a36d1ff965618c. Seemingly, it was not used at all.
