### ISSUE TITLE
Espo V8.3.X - Regular users can't see a Team's users

### ISSUE THREAD

**Issue by kboykov** [espocrm/espocrm#3091]
**Describe the bug**
Before v8.3.0 a regular user was able to go to /#Team, click on a team and preview all the users associated with that team. Currently this is not possible and a JS error appears in the console.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Go to /#Team as a regular (non-admin) user
2. Choose a team and open it up
3. The bottom panel which lists associated users cannot be loaded

Additionally, this JS errors appears in the console:

espo-main.js:29748 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at s.data (espo-main.js:29748:12)
    at s._getData (bullbone.js:1574:29)
    at bullbone.js:1659:37
    at s (bullbone.js:1613:21)
    at s._getNestedViewsHtmlMap (bullbone.js:1617:13)
    at s._getHtml (bullbone.js:1658:18)
    at s.getHtml (bullbone.js:1183:18)
    at bullbone.js:1634:22
    at Array.forEach (<anonymous>)
    at s._getNestedViewsHtmlMap (bullbone.js:1619:19)

**Expected behavior**
The bottom panel should be able to load as before v8.3.0

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/66499378/de0d16a7-e050-4095-b3b4-f46cb8437fe2)

**EspoCRM version**
v8.3.2

**Additional context**
I tried looking up in the Espo logs but nothing appears there... I think it is a problem on the front-end part.

**Comment by kboykov** [comment]
Additional context: 

For some reason when reproducing the steps as an admin, there is no problem and users load without problem
