### ISSUE TITLE
Urgent Issue: Issue While Installing ESPO Crm 3.1.1.

### ISSUE THREAD

**Issue by atapatel** [espocrm/espocrm#39]
Hi 
We are facing an issue while installing ESPOCRM 3.1.1. After Providing a Database detail it shows us a Ajax Failed Error. We have worked out some log file related things please have a look for same.

```
[2015-04-08 10:39:05] Espo.ALERT: Rebuild database fault: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes' in /var/www/html/espocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:699
Stack trace:
#0 /var/www/html/espocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(699): PDO->query('CREATE TABLE no...')
#1 /var/www/html/espocrm/application/Espo/Core/Utils/Database/Schema/Schema.php(203): Doctrine\DBAL\Connection->executeQuery('CREATE TABLE no...')
#2 /var/www/html/espocrm/install/core/Installer.php(209): Espo\Core\Utils\Database\Schema\Schema->rebuild()
#3 /var/www/html/espocrm/install/core/actions/buildDatabse.php(26): Installer->buildDatabase()
#4 /var/www/html/espocrm/install/index.php(135): include('/var/www...')
#5 {main}

Next exception 'Doctrine\DBAL\DBALException' with message 'An exception occurred while executing 'CREATE TABLE note (id VARCHAR(24) NOT NULL, post LONGTEXT DEFAULT NULL, data LONGTEXT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, number INT AUTO_INCREMENT NOT NULL UNIQUE, created_at DATETIME DEFAULT NULL, modified_at DATETIME DEFAULT NULL, deleted TINYINT(1) DEFAULT '0', super_parent_id VARCHAR(24) DEFAULT NULL, super_parent_type VARCHAR(255) DEFAULT NULL, parent_id VARCHAR(24) DEFAULT NULL, parent_type VARCHAR(255) DEFAULT NULL, modified_by_id VARCHAR(24) DEFAULT NULL, created_by_id VARCHAR(24) DEFAULT NULL, INDEX `superParent` (super_parent_id, super_parent_type), INDEX `parent` (parent_id, parent_type), INDEX `modifiedBy` (modified_by_id), INDEX `createdBy` (created_by_id), INDEX `IDX_NOTE_CREATED_AT` (created_at), INDEX `IDX_NOTE_PARENT_AND_SUPER_PARENT` (parent_id, parent_type, super_parent_id, super_parent_type), UNIQUE INDEX `UNIQ_CFBDFA1496901F54` (number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = MyISAM':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes' in /var/www/html/espocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91
Stack trace:
#0 /var/www/html/espocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(702): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(PDOException), 'CREATE TABLE no...', Array)
#1 /var/www/html/espocrm/application/Espo/Core/Utils/Database/Schema/Schema.php(203): Doctrine\DBAL\Connection->executeQuery('CREATE TABLE no...')
#2 /var/www/html/espocrm/install/core/Installer.php(209): Espo\Core\Utils\Database\Schema\Schema->rebuild()
#3 /var/www/html/espocrm/install/core/actions/buildDatabse.php(26): Installer->buildDatabase()
#4 /var/www/html/espocrm/install/index.php(135): include('/var/www...')
#5 {main} [] []
[2015-04-08 10:39:05] Espo.ERROR: Uncaught exception {"exception":"[object] (PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user.avatar' in 'field list' at /var/www/html/espocrm/application/Espo/ORM/DB/Mapper.php:96)"} []
```

**Comment by yurikuzn** [comment]
Hi

Is it dev version? We have fixed this issue already.

**Comment by atapatel** [comment]
hi can u please share me which branch is production ready ?

**Comment by yurikuzn** [comment]
You can build from the last release tag (3.1.1 for now). Or download the latest version http://www.espocrm.com/download/
